[package]
name = "sqlite-geob"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.37", features = ["loadable_extension", "functions"] }
rusqlite-geob = { path = "../rusqlite-geob" }
